# Source language and JDK version to use.
language: java
jdk: oraclejdk7

# Include JavaFX in the JDK's classpath.
before_script: mvn jfx:fix-classpath -DsilentJfxFix=true
# Compile and package an executable JavaFX JAR and set build properties.
install: mvn javafx:jar -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}

notifications:
  # Disable build status email notifications, until the issue with forks is fixed.
  email: false
  webhooks:
    - http://get.spout.org/hook
    - http://n.tkte.ch/h/1249/zmskwpaqEyBNbLZGHsIzwvVz
